name: Build UE5 Project

on:
  push:
    branches: [ main, project-build ]
  pull_request:
    branches: [ main, project-build ]

# Je vais changer ça après pour qu'on puisse build en release sur main
# et en dev sur project-build ou une autre branche
env:
  BUILD_CONFIG: Development  # Development/Shipping

jobs:
  build:
    name: Build Project
    runs-on: [self-hosted, windows]
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Environment Variables
      shell: powershell
      run: |
        "UE_ENGINE_PATH=D:\Software\UE_5.4" | Out-File -FilePath $env:GITHUB_ENV -Append
        "PROJECT_PATH=${{ github.workspace }}\ErethiaUnreal.uproject" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Build Unreal Engine Editor (Blueprint Projects)
      shell: cmd
      run: |
        "%UE_ENGINE_PATH%\Engine\Build\BatchFiles\Build.bat" ErethiaUnrealEditor Win64 %BUILD_CONFIG% -project="%PROJECT_PATH%"

    - name: Cook & Package (${{ env.BUILD_CONFIG }})
      shell: cmd
      run: |
        set FLAGS=-nocompileeditor -cook -allmaps -build -stage -pak -archive
        if "%BUILD_CONFIG%"=="Shipping" set FLAGS=%FLAGS% -compressed -prereqs -nodebuginfo
        "%UE_ENGINE_PATH%\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun ^
          -project="%PROJECT_PATH%" ^
          -noP4 -platform=Win64 ^
          -clientconfig=%BUILD_CONFIG% -serverconfig=%BUILD_CONFIG% ^
          %FLAGS% ^
          -archivedirectory="%GITHUB_WORKSPACE%\Build%BUILD_CONFIG%"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UE5-Build
        path: BuildOutput
        if-no-files-found: warn
