name: Build UE5 Project

on:
  push:
    branches: [ main, project-build ]
  pull_request:
    branches: [ main, project-build ]

jobs:
  build:
    name: Build Project
    runs-on: [self-hosted, windows]
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Environment Variables
      shell: pwsh
      run: |
        "UE_ENGINE_PATH=D:\Software\UE_5.4" | Out-File -FilePath $env:GITHUB_ENV -Append
        "PROJECT_PATH=${{ github.workspace }}\ErethiaUnreal.uproject" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Generate Project Files
      shell: cmd
      run: |
        "%UE_ENGINE_PATH%\Engine\Build\BatchFiles\GenerateProjectFiles.bat" "%PROJECT_PATH%"

    - name: Build Project (Development)
      shell: cmd
      run: |
        "%UE_ENGINE_PATH%\Engine\Build\BatchFiles\Build.bat" ErethiaUnrealEditor Win64 Development "%PROJECT_PATH%"

    - name: Package Project
      run: |
        & "$Env:UE_ENGINE_PATH\Engine\Build\BatchFiles\RunUAT.bat" BuildCookRun ^
          -project="$Env:PROJECT_PATH" ^
          -noP4 -platform=Win64 -clientconfig=Development -serverconfig=Development ^
          -cook -allmaps -build -stage -pak -archive ^
          -archivedirectory="${{ github.workspace }}\BuildOutput"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: UE5-Build
        path: BuildOutput
        if-no-files-found: warn
