name: Create Issues from GitHub Project

on:
  schedule:
    - cron: "0 * * * *"  # run toutes les heures
  workflow_dispatch:

jobs:
  create-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Run issue sync script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECTS_PAT }}
          script: |
            const projectNumber = 14;
            const org = 'Erethia-Education-Quest';
            const repo = 'Erethia-Unreal';

            const query = `
              query($org: String!, $number: Int!) {
                organization(login: $org) {
                  projectV2(number: $number) {
                    items(first: 100) {
                      nodes {
                        id
                        content {
                          ... on DraftIssue {
                            title
                            body
                          }
                          ... on Issue {
                            number
                          }
                        }
                        fieldValues(first: 20) {
                          nodes {
                            ... on ProjectV2ItemFieldSingleSelectValue {
                              name
                              field {
                                ... on ProjectV2SingleSelectField {
                                  name
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;

            const variables = {
              org,
              number: projectNumber
            };

            const result = await github.graphql(query, variables);
            const items = result.organization.projectV2.items.nodes;

            for (const item of items) {
              // Check if already linked to an issue
              if (item.content?.number) {
                console.log(`Item already linked to Issue #${item.content.number}, skipping.`);
                continue;
              }

              const statusField = item.fieldValues.nodes.find(
                f => f.field?.name === "Status"
              );

              if (statusField?.name !== "Ready") {
                console.log(`Item skipped (status not Ready)`);
                continue;
              }

              const title = item.content?.title || "Untitled";
              const body = item.content?.body || "Auto-generated from GitHub Project";

              const issue = await github.rest.issues.create({
                owner: org,
                repo,
                title,
                body
              });

              console.log(`Created issue #${issue.data.number}: ${title}`);
            }
